const $=id=>document.getElementById(id);
let rows=[],filtered=[];
const plotCfg={displaylogo:false,responsive:true};
const layoutBase={paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dceaff',family:'Inter,Arial'},margin:{l:45,r:18,t:20,b:55},xaxis:{gridcolor:'rgba(255,255,255,.07)',zerolinecolor:'rgba(255,255,255,.08)'},yaxis:{gridcolor:'rgba(255,255,255,.07)',zerolinecolor:'rgba(255,255,255,.08)'},legend:{orientation:'h',y:1.13}};
const num=v=>{if(v==null||v==='')return 0;const n=Number(String(v).replace(/[,\s$%]/g,'').replace(/\((.*)\)/,'-$1'));return Number.isFinite(n)?n:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n||0);
const pct=n=>Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(1)}%`:'—';
const norm=s=>String(s??'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');
const monthMap={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12,jan:1,feb:2,mar:3,apr:4,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};
function monthNo(v){if(typeof v==='number')return v;const s=norm(v);return monthMap[s]||monthMap[s.slice(0,3)]||0}
function returnBand(v){v=Math.abs(num(v));if(v===0)return '0';if(v<1000)return '1–999';if(v<5000)return '1,000–4,999';if(v<10000)return '5,000–9,999';return '10,000+'}
const aliases={year:['year'],month:['month'],rep:['sales res. name','sales rep. name','sales rep name'],zone:['zone name','zone'],state:['state'],name:['name','pharmacy','pharmacy name','customer name'],sales:['net amount (invoiced)','sold amount (invoiced)','sales value'],returns:['returned amount (invoiced)','sales return value']};
function cellValue(ws,r,c){const cell=ws[XLSX.utils.encode_cell({r,c})];return cell?cell.v:''}
function detectHeader(ws){const range=XLSX.utils.decode_range(ws['!ref']||'A1:A1'),maxC=Math.min(range.e.c,60);for(let r=range.s.r;r<=Math.min(range.e.r,range.s.r+7);r++){const headers=[];for(let c=range.s.c;c<=maxC;c++)headers.push(norm(cellValue(ws,r,c)));if(headers.includes('year')&&headers.includes('name')&&headers.includes('state')&&headers.some(x=>x.includes('net amount (invoiced)')))return r}return -1}
function findSheet(wb){for(const s of wb.SheetNames){const ws=wb.Sheets[s],headerRow=detectHeader(ws);if(headerRow>=0)return{ws,headerRow,sheetName:s}}return null}
function getColumnMap(ws,headerRow){const range=XLSX.utils.decode_range(ws['!ref']||'A1:A1'),out={};for(let c=range.s.c;c<=range.e.c;c++){const h=norm(cellValue(ws,headerRow,c));for(const[k,names]of Object.entries(aliases)){if(out[k]==null&&names.map(norm).includes(h))out[k]=c}}return out}
function parseWorksheet(found,fileName){const{ws,headerRow}=found,range=XLSX.utils.decode_range(ws['!ref']||'A1:A1'),cm=getColumnMap(ws,headerRow);if(cm.year==null||cm.month==null||cm.name==null||cm.state==null||cm.sales==null)throw new Error(`Required columns not found in ${fileName}`);const out=[];for(let r=headerRow+1;r<=range.e.r;r++){const year=Number(cellValue(ws,r,cm.year));if(year!==2025&&year!==2026)continue;const month=monthNo(cellValue(ws,r,cm.month));if(month<1||month>8)continue;const sales=num(cellValue(ws,r,cm.sales)),returns=cm.returns==null?0:Math.abs(num(cellValue(ws,r,cm.returns))),rep=String(cm.rep==null?'Unknown':cellValue(ws,r,cm.rep)).trim()||'Unknown',zone=String(cm.zone==null?'Unknown':cellValue(ws,r,cm.zone)).trim()||'Unknown',state=String(cellValue(ws,r,cm.state)).trim()||'Unknown',name=String(cellValue(ws,r,cm.name)).trim()||'Unknown';out.push({__d:{year,month,rep,zone,state,name,sales,returns}})}return out}
const wait=()=>new Promise(r=>setTimeout(r,30));
async function loadFiles(files){rows=[];clearFilterState();$('dashboard').classList.add('hidden');$('status').textContent='Reading files…';let loaded=[];try{for(let i=0;i<files.length;i++){const file=files[i];$('status').textContent=`Reading ${i+1}/${files.length}: ${file.name}…`;await wait();const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:false,dense:false}),found=findSheet(wb);if(!found){loaded.push(`${file.name}: sheet not found`);continue}$('status').textContent=`Processing ${file.name} (${found.sheetName})…`;await wait();const prepared=parseWorksheet(found,file.name);rows.push(...prepared);loaded.push(`${file.name}: ${fmt(prepared.length)} rows`);await wait()}if(!rows.length){$('status').textContent='No Jan–Aug 2025/2026 sales rows found.';return}$('status').textContent=`Building optimized filters for ${fmt(rows.length)} rows…`;await wait();$('dashboard').classList.remove('hidden');applyFilters();$('status').textContent=`Loaded ${fmt(rows.length)} rows • ${loaded.join(' • ')}`;}catch(err){console.error(err);$('status').textContent=`Error: ${err.message}`;alert(`Could not load the files: ${err.message}`)}}

const filterDefs=[['fRep','rep','sRep'],['fZone','zone','sZone'],['fState','state','sState'],['fName','name','sName'],['fReturn','returnBand','sReturn']];
const filterState=Object.fromEntries(filterDefs.map(([id])=>[id,new Set()]));
let optionSets=filterDefs.map(()=>new Set());
const MAX_VISIBLE=150;
function clearFilterState(){for(const [id,,searchId] of filterDefs){filterState[id].clear();if($(searchId))$(searchId).value=''}}
function filterValue(r,k){return k==='returnBand'?returnBand(r.__d.returns):r.__d[k]}
function renderOneFilter(index){const[id,,searchId]=filterDefs[index],q=$(searchId).value.trim().toLowerCase(),selected=filterState[id],all=[...optionSets[index]].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})),matches=q?all.filter(v=>String(v).toLowerCase().includes(q)):all;const selectedFirst=[...selected].filter(v=>!q||String(v).toLowerCase().includes(q));const seen=new Set(selectedFirst);const visible=[...selectedFirst,...matches.filter(v=>!seen.has(v))].slice(0,MAX_VISIBLE);const list=$(id);list.innerHTML=visible.length?visible.map(v=>`<label class="check-item"><input type="checkbox" value="${esc(v)}" ${selected.has(v)?'checked':''}><span class="check-text">${esc(v)}</span></label>`).join(''):'<div class="check-empty">No matches</div>';const meta=document.createElement('div');meta.className='check-meta';meta.textContent=matches.length>MAX_VISIBLE?`Showing ${Math.min(MAX_VISIBLE,visible.length)} of ${fmt(matches.length)} — use search to narrow`:`${fmt(matches.length)} option${matches.length===1?'':'s'}`;list.appendChild(meta)}
function renderAllFilters(){for(let i=0;i<filterDefs.length;i++)renderOneFilter(i)}
function applyFilters(){optionSets=filterDefs.map(()=>new Set());filtered=[];const states=filterDefs.map(([id])=>filterState[id]);for(const r of rows){const vals=[r.__d.rep,r.__d.zone,r.__d.state,r.__d.name,returnBand(r.__d.returns)];let failCount=0,failIndex=-1;for(let i=0;i<states.length;i++){const s=states[i];if(s.size&&!s.has(vals[i])){failCount++;failIndex=i;if(failCount>1)break}}if(failCount===0){filtered.push(r);for(let i=0;i<vals.length;i++)optionSets[i].add(vals[i])}else if(failCount===1){optionSets[failIndex].add(vals[failIndex])}}for(let i=0;i<filterDefs.length;i++){for(const v of states[i])optionSets[i].add(v)}renderAllFilters();render()}

function aggregate(data,key){const m=new Map();for(const r of data){const k=r.__d[key];if(!m.has(k))m.set(k,{key:k,s25:0,s26:0,ret26:0});const x=m.get(k);if(r.__d.year===2025)x.s25+=r.__d.sales;else{x.s26+=r.__d.sales;x.ret26+=r.__d.returns}}return[...m.values()].map(x=>({...x,growth:x.s25?((x.s26-x.s25)/x.s25*100):(x.s26>0?100:null)}))}
function pharmacyAgg(data){const m=new Map();for(const r of data){const k=[r.__d.name,r.__d.state,r.__d.zone].join('|||');if(!m.has(k))m.set(k,{name:r.__d.name,state:r.__d.state,zone:r.__d.zone,s25:0,s26:0,ret26:0});const x=m.get(k);if(r.__d.year===2025)x.s25+=r.__d.sales;else{x.s26+=r.__d.sales;x.ret26+=r.__d.returns}}return[...m.values()].map(x=>({...x,growth:x.s25?((x.s26-x.s25)/x.s25*100):(x.s26>0?100:null)}))}
function render(){const d=filtered;let s25=0,s26=0,ret26=0;for(const r of d){if(r.__d.year===2025)s25+=r.__d.sales;else{s26+=r.__d.sales;ret26+=r.__d.returns}}const g=s25?((s26-s25)/s25*100):0,p=pharmacyAgg(d);$('k25').textContent=fmt(s25);$('k26').textContent=fmt(s26);$('kGrowth').textContent=pct(g);$('kGrowth').className=g>=0?'pos':'neg';$('kReturn').textContent=s26?`${(ret26/s26*100).toFixed(2)}%`:'—';$('k10k').textContent=fmt(p.filter(x=>x.s26>=10000).length);renderMonthly(d);renderBars(d,'state','stateChart');renderBars(d,'zone','zoneChart');renderReturns(d);renderLeaderboards(p);renderTables(p)}
function renderMonthly(d){const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug'],s25=Array(8).fill(0),s26=Array(8).fill(0);for(const r of d){const i=r.__d.month-1;if(i<0||i>7)continue;(r.__d.year===2025?s25:s26)[i]+=r.__d.sales}Plotly.react('monthlyChart',[{x:months,y:s25,name:'2025',type:'bar',marker:{color:'#6c7cff'}},{x:months,y:s26,name:'2026',type:'bar',marker:{color:'#3cf6ff'}}],{...layoutBase,barmode:'group'},plotCfg)}
function renderBars(d,key,id){const a=aggregate(d,key).sort((x,y)=>y.s26-x.s26).slice(0,15);Plotly.react(id,[{x:a.map(x=>x.key),y:a.map(x=>x.s25),name:'2025',type:'bar',marker:{color:'#6c7cff'}},{x:a.map(x=>x.key),y:a.map(x=>x.s26),name:'2026',type:'bar',marker:{color:'#3cf6ff'}}],{...layoutBase,barmode:'group'},plotCfg)}
function renderReturns(d){const a=aggregate(d,'state').sort((x,y)=>y.ret26-x.ret26).slice(0,12);Plotly.react('returnChart',[{x:a.map(x=>x.key),y:a.map(x=>x.ret26),type:'bar',name:'Returned Amount 2026',marker:{color:'#ff4fd8'}}],layoutBase,plotCfg)}
function renderLeaderboards(p){const states=[...new Set(p.map(x=>x.state))].sort(),curr=$('leaderState').value;$('leaderState').innerHTML=['All States',...states].map(s=>`<option ${s===curr?'selected':''}>${esc(s)}</option>`).join('');if(!$('leaderState').value)$('leaderState').value='All States';const q=$('leaderState').value==='All States'?p:p.filter(x=>x.state===$('leaderState').value),grow=q.filter(x=>x.s25>0&&x.growth>=10).sort((a,b)=>b.growth-a.growth).slice(0,10),decl=q.filter(x=>x.s25>0&&x.growth<=-10).sort((a,b)=>a.growth-b.growth).slice(0,10),horiz=(id,a,color)=>Plotly.react(id,[{y:a.map(x=>x.name).reverse(),x:a.map(x=>x.growth).reverse(),type:'bar',orientation:'h',text:a.map(x=>pct(x.growth)).reverse(),textposition:'auto',marker:{color}}],{...layoutBase,margin:{l:150,r:20,t:15,b:35},showlegend:false},plotCfg);horiz('growthChart',grow,'#42ffb3');horiz('declineChart',decl,'#ff5f7a')}
function renderTables(p){const q=$('pharmacySearch').value.toLowerCase(),list=p.filter(x=>x.name.toLowerCase().includes(q)).sort((a,b)=>b.s26-a.s26);$('pharmacyTable').querySelector('tbody').innerHTML=list.slice(0,500).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.state)}</td><td>${esc(x.zone)}</td><td>${fmt(x.s25)}</td><td>${fmt(x.s26)}</td><td class="${(x.growth||0)>=0?'pos':'neg'}">${pct(x.growth)}</td><td>${fmt(x.ret26)}</td></tr>`).join('');$('highTable').querySelector('tbody').innerHTML=p.filter(x=>x.s26>=10000).sort((a,b)=>b.s26-a.s26).slice(0,500).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.state)}</td><td>${fmt(x.s25)}</td><td>${fmt(x.s26)}</td><td class="${(x.growth||0)>=0?'pos':'neg'}">${pct(x.growth)}</td></tr>`).join('')}

$('fileInput').addEventListener('change',e=>e.target.files.length&&loadFiles([...e.target.files]));
$('dropZone').addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.style.borderColor='#3cf6ff'});
$('dropZone').addEventListener('dragleave',e=>e.currentTarget.style.borderColor='');
$('dropZone').addEventListener('drop',e=>{e.preventDefault();e.currentTarget.style.borderColor='';e.dataTransfer.files.length&&loadFiles([...e.dataTransfer.files])});
for(let i=0;i<filterDefs.length;i++){const[id,,searchId]=filterDefs[i];$(id).addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;const s=filterState[id];e.target.checked?s.add(e.target.value):s.delete(e.target.value);applyFilters()});$(searchId).addEventListener('input',()=>renderOneFilter(i))}
$('leaderState').addEventListener('change',()=>renderLeaderboards(pharmacyAgg(filtered)));
$('pharmacySearch').addEventListener('input',()=>renderTables(pharmacyAgg(filtered)));
$('resetFilters').addEventListener('click',()=>{clearFilterState();applyFilters()});
